project:
  type: website
  output-dir: docs


website:
  title: "BEyond"
  navbar:
    left: 
      - text: Überblick
        file: index.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



