---
title: "BEyond Rapidsurvey Schorfheide"
---



```{r}
#| echo: false
#| include: false
#| message: false
#| warning: false

library(tidyverse)
library(sf)
library(mapview)
library(gt)
```


```{r}
#| echo: false
#| message: false
#| warning: false

dlm = read_sf("~/beyond/be_rapidsurvey_schorfheide/valid_grasslands.gpkg")
dlm_crs = st_crs(dlm)

explo_sch = read_sf("~/beyond/data/Basisdaten/studyarea/geometrien_exploratorien.gpkg", layer = "area_sch")
explo_sch = st_transform(explo_sch, dlm_crs)

kreise = read_sf("~/beyond/be_rapidsurvey_schorfheide/germany_gadm_l2.gpkg")
kreise = kreise |> filter(NAME_2 != "Oberhavel") |> st_transform(dlm_crs)

naturraum = read_sf("~/data/germany/germany_naturraeume.gpkg")
naturraum = naturraum |> filter(ZUS %in% c("D04", "D03")) |> st_transform(dlm_crs)

schutzgebiete = read_sf("~/data/germany/germany_naturschutzgebiete.gpkg")
schutzgebiete = st_transform(schutzgebiete, dlm_crs) |> st_zm()
schutzgebiete = schutzgebiete[kreise,]


rapidsurvey = read_sf("~/beyond/be_rapidsurvey_schorfheide/rapidsurvey_plots.gpkg")
rapidsurvey_alternative = read_sf("~/beyond/be_rapidsurvey_schorfheide/rapidsurvey_plots_add.gpkg")

```






```{r}
#| message: false
#| warning: false
#| echo: false

mapviewOptions(basemaps = c("OpenStreetMap.DE","CartoDB.Positron","Esri.WorldImagery"))

#mapview(dlm, col.regions = "lightgreen", layer.name = "DLM Grasslands") +
mapview(explo_sch, col.regions = "lightyellow", layer.name = "Exploratorium")+
  mapview(schutzgebiete, col.regions = "lightblue")+
  mapview(rapidsurvey, col.regions = "black") + 
  mapview(rapidsurvey_alternative, col.regions = "white")

```


## Rapidsurvey plots

```{r}
#| echo: false
rapidsurvey |> gt()
```


## Alternative plots

```{r}
#| echo: false
rapidsurvey_alternative |> gt()
```


